# 直接定义SIXTY_FOUR_GUA字典内容
old_dict_str = '''{
    # 乾宫八卦（完整）
    "乾为天": {"code": "111111", "upper": "乾", "lower": "乾", "number": 1, "sequence": 1, "palace": "乾",
               "nature": "乾健", "attribute": "纯阳", "gua_ci": "元亨利贞",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["甲", "甲", "甲", "壬", "壬", "壬"],
               "branches": ["子", "寅", "辰", "午", "申", "戌"],
               "liu_qin": ["子孙", "妻财", "父母", "官鬼", "兄弟", "父母"]},
    "天风姤": {"code": "011111", "upper": "乾", "lower": "巽", "number": 44, "sequence": 2, "palace": "乾",
               "nature": "天下有风", "attribute": "消息卦", "gua_ci": "女壮，勿用取女",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["辛", "辛", "辛", "壬", "壬", "壬"],
               "branches": ["丑", "亥", "酉", "午", "申", "戌"],
               "liu_qin": ["父母", "子孙", "兄弟", "官鬼", "兄弟", "父母"]},
    "天山遁": {"code": "001111", "upper": "乾", "lower": "艮", "number": 33, "sequence": 3, "palace": "乾",
               "nature": "天下有山", "attribute": "退避", "gua_ci": "亨，小利贞",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["丙", "丙", "丙", "壬", "壬", "壬"],
               "branches": ["辰", "午", "申", "午", "申", "戌"],
               "liu_qin": ["父母", "官鬼", "兄弟", "官鬼", "兄弟", "父母"]},
    "天地否": {"code": "000111", "upper": "乾", "lower": "坤", "number": 12, "sequence": 4, "palace": "乾",
               "nature": "天地不交", "attribute": "闭塞", "gua_ci": "否之匪人，不利君子贞",
               "shi_yao": 3, "shi_type": "三世",
               "stems": ["乙", "乙", "乙", "壬", "壬", "壬"],
               "branches": ["未", "巳", "卯", "午", "申", "戌"],
               "liu_qin": ["父母", "官鬼", "妻财", "官鬼", "兄弟", "父母"]},
    "风地观": {"code": "000011", "upper": "巽", "lower": "坤", "number": 20, "sequence": 5, "palace": "乾",
               "nature": "风行地上", "attribute": "观察", "gua_ci": "盥而不荐，有孚颙若",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["乙", "乙", "乙", "辛", "辛", "辛"],
               "branches": ["未", "巳", "卯", "未", "巳", "卯"],
               "liu_qin": ["父母", "官鬼", "妻财", "父母", "官鬼", "妻财"]},
    "山地剥": {"code": "000001", "upper": "艮", "lower": "坤", "number": 23, "sequence": 6, "palace": "乾",
               "nature": "山附于地", "attribute": "剥落", "gua_ci": "不利有攸往",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["乙", "乙", "乙", "丙", "丙", "丙"],
               "branches": ["未", "巳", "卯", "戌", "子", "寅"],
               "liu_qin": ["父母", "官鬼", "妻财", "父母", "子孙", "妻财"]},
    "火地晋": {"code": "000101", "upper": "离", "lower": "坤", "number": 35, "sequence": 7, "palace": "乾",
               "nature": "明出地上", "attribute": "前进", "gua_ci": "康侯用锡马蕃庶，昼日三接",
               "shi_yao": 4, "shi_type": "游魂",
               "stems": ["乙", "乙", "乙", "己", "己", "己"],
               "branches": ["未", "巳", "卯", "酉", "未", "巳"],
               "liu_qin": ["父母", "官鬼", "妻财", "兄弟", "父母", "官鬼"]},
    "火天大有": {"code": "111101", "upper": "离", "lower": "乾", "number": 14, "sequence": 8, "palace": "乾",
                 "nature": "火在天上", "attribute": "丰盛", "gua_ci": "元亨",
                 "shi_yao": 3, "shi_type": "归魂",
                 "stems": ["甲", "甲", "甲", "己", "己", "己"],
                 "branches": ["子", "寅", "辰", "酉", "未", "巳"],
                 "liu_qin": ["子孙", "妻财", "父母", "兄弟", "父母", "官鬼"]},

    # 兑宫八卦（完整）
    "兑为泽": {"code": "110110", "upper": "兑", "lower": "兑", "number": 58, "sequence": 9, "palace": "兑",
               "nature": "丽泽", "attribute": "悦乐", "gua_ci": "亨，利贞",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["丁", "丁", "丁", "丁", "丁", "丁"],
               "branches": ["巳", "卯", "丑", "亥", "酉", "未"],
               "liu_qin": ["官鬼", "妻财", "父母", "子孙", "兄弟", "父母"]},
    "泽水困": {"code": "010110", "upper": "兑", "lower": "坎", "number": 47, "sequence": 10, "palace": "兑",
               "nature": "泽无水", "attribute": "困顿", "gua_ci": "亨，贞，大人吉，无咎",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["戊", "戊", "戊", "丁", "丁", "丁"],
               "branches": ["寅", "辰", "午", "亥", "酉", "未"],
               "liu_qin": ["妻财", "父母", "官鬼", "子孙", "兄弟", "父母"]},
    "泽地萃": {"code": "000110", "upper": "兑", "lower": "坤", "number": 45, "sequence": 11, "palace": "兑",
               "nature": "泽于地", "attribute": "聚集", "gua_ci": "亨，王假有庙",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["乙", "乙", "乙", "丁", "丁", "丁"],
               "branches": ["未", "巳", "卯", "亥", "酉", "未"],
               "liu_qin": ["父母", "官鬼", "妻财", "子孙", "兄弟", "父母"]},
    "泽山咸": {"code": "001110", "upper": "兑", "lower": "艮", "number": 31, "sequence": 12, "palace": "兑",
               "nature": "山泽通气", "attribute": "感应", "gua_ci": "亨，利贞，取女吉",
               "shi_yao": 3, "shi_type": "三世",
               "stems": ["丙", "丙", "丙", "丁", "丁", "丁"],
               "branches": ["辰", "午", "申", "亥", "酉", "未"],
               "liu_qin": ["父母", "官鬼", "兄弟", "子孙", "兄弟", "父母"]},
    "水山蹇": {"code": "001010", "upper": "坎", "lower": "艮", "number": 39, "sequence": 13, "palace": "兑",
               "nature": "山上有水", "attribute": "艰难", "gua_ci": "利西南，不利东北",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["丙", "丙", "丙", "戊", "戊", "戊"],
               "branches": ["辰", "午", "申", "申", "戌", "子"],
               "liu_qin": ["父母", "官鬼", "兄弟", "兄弟", "父母", "子孙"]},
    "地山谦": {"code": "001000", "upper": "坤", "lower": "艮", "number": 15, "sequence": 14, "palace": "兑",
               "nature": "地中有山", "attribute": "谦虚", "gua_ci": "亨，君子有终",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["丙", "丙", "丙", "癸", "癸", "癸"],
               "branches": ["辰", "午", "申", "丑", "亥", "酉"],
               "liu_qin": ["父母", "官鬼", "兄弟", "父母", "子孙", "兄弟"]},
    "雷山小过": {"code": "001100", "upper": "震", "lower": "艮", "number": 62, "sequence": 15, "palace": "兑",
                 "nature": "山上有雷", "attribute": "小有过失", "gua_ci": "亨，利贞",
                 "shi_yao": 4, "shi_type": "游魂",
                 "stems": ["丙", "丙", "丙", "庚", "庚", "庚"],
                 "branches": ["辰", "午", "申", "午", "申", "戌"],
                 "liu_qin": ["父母", "官鬼", "兄弟", "官鬼", "兄弟", "父母"]},
    "雷泽归妹": {"code": "110100", "upper": "震", "lower": "兑", "number": 54, "sequence": 16, "palace": "兑",
                 "nature": "泽上有雷", "attribute": "婚嫁", "gua_ci": "征凶，无攸利",
                 "shi_yao": 3, "shi_type": "归魂",
                 "stems": ["丁", "丁", "丁", "庚", "庚", "庚"],
                 "branches": ["巳", "卯", "丑", "午", "申", "戌"],
                 "liu_qin": ["官鬼", "妻财", "父母", "官鬼", "兄弟", "父母"]},

    # 离宫八卦（完整）
    "离为火": {"code": "101101", "upper": "离", "lower": "离", "number": 30, "sequence": 17, "palace": "离",
               "nature": "明两作", "attribute": "附丽", "gua_ci": "利贞，亨",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["己", "己", "己", "己", "己", "己"],
               "branches": ["卯", "丑", "亥", "酉", "未", "巳"],
               "liu_qin": ["父母", "妻财", "官鬼", "妻财", "子孙", "兄弟"]},
    "火山旅": {"code": "001101", "upper": "离", "lower": "艮", "number": 56, "sequence": 18, "palace": "离",
               "nature": "山上有火", "attribute": "旅行", "gua_ci": "小亨，旅贞吉",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["丙", "丙", "丙", "己", "己", "己"],
               "branches": ["辰", "午", "申", "酉", "未", "巳"],
               "liu_qin": ["子孙", "兄弟", "妻财", "妻财", "子孙", "兄弟"]},
    "火风鼎": {"code": "011101", "upper": "离", "lower": "巽", "number": 50, "sequence": 19, "palace": "离",
               "nature": "木上有火", "attribute": "鼎新", "gua_ci": "元吉，亨",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["辛", "辛", "辛", "己", "己", "己"],
               "branches": ["丑", "亥", "酉", "酉", "未", "巳"],
               "liu_qin": ["子水", "官鬼", "妻财", "妻财", "子孙", "兄弟"]},
    "火水未济": {"code": "010101", "upper": "离", "lower": "坎", "number": 64, "sequence": 20, "palace": "离",
                 "nature": "火在水上", "attribute": "未完成", "gua_ci": "亨，小狐汔济",
                 "shi_yao": 3, "shi_type": "三世",
                 "stems": ["戊", "戊", "戊", "己", "己", "己"],
                 "branches": ["寅", "辰", "午", "酉", "未", "巳"],
                 "liu_qin": ["父母", "子孙", "兄弟", "妻财", "子孙", "兄弟"]},
    "山水蒙": {"code": "010001", "upper": "艮", "lower": "坎", "number": 4, "sequence": 21, "palace": "离",
               "nature": "山下出泉", "attribute": "蒙昧", "gua_ci": "亨。匪我求童蒙，童蒙求我",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["戊", "戊", "戊", "丙", "丙", "丙"],
               "branches": ["寅", "辰", "午", "戌", "子", "寅"],
               "liu_qin": ["父母", "子孙", "兄弟", "子孙", "官鬼", "父母"]},
    "风水涣": {"code": "010011", "upper": "巽", "lower": "坎", "number": 59, "sequence": 22, "palace": "离",
               "nature": "风行水上", "attribute": "涣散", "gua_ci": "亨。王假有庙",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["戊", "戊", "戊", "辛", "辛", "辛"],
               "branches": ["寅", "辰", "午", "未", "巳", "卯"],
               "liu_qin": ["父母", "子孙", "兄弟", "子孙", "兄弟", "父母"]},
    "天水讼": {"code": "010111", "upper": "乾", "lower": "坎", "number": 6, "sequence": 23, "palace": "离",
               "nature": "天与水违行", "attribute": "争讼", "gua_ci": "有孚，窒惕，中吉",
               "shi_yao": 4, "shi_type": "游魂",
               "stems": ["戊", "戊", "戊", "壬", "壬", "壬"],
               "branches": ["寅", "辰", "午", "午", "申", "戌"],
               "liu_qin": ["父母", "子孙", "兄弟", "兄弟", "妻财", "子孙"]},
    "天火同人": {"code": "101111", "upper": "乾", "lower": "离", "number": 13, "sequence": 24, "palace": "离",
                 "nature": "天与火", "attribute": "同心", "gua_ci": "同人于野，亨",
                 "shi_yao": 3, "shi_type": "归魂",
                 "stems": ["己", "己", "己", "壬", "壬", "壬"],
                 "branches": ["卯", "丑", "亥", "午", "申", "戌"],
                 "liu_qin": ["父母", "子孙", "官鬼", "兄弟", "妻财", "子孙"]},

    # 震宫八卦（完整）
    "震为雷": {"code": "100100", "upper": "震", "lower": "震", "number": 51, "sequence": 25, "palace": "震",
               "nature": "洊雷", "attribute": "震动", "gua_ci": "亨，震来虩虩，笑言哑哑",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["庚", "庚", "庚", "庚", "庚", "庚"],
               "branches": ["子", "寅", "辰", "午", "申", "戌"],
               "liu_qin": ["父母", "兄弟", "妻财", "子孙", "官鬼", "妻财"]},
    "雷地豫": {"code": "000100", "upper": "震", "lower": "坤", "number": 16, "sequence": 26, "palace": "震",
               "nature": "雷出地奋", "attribute": "愉悦", "gua_ci": "利建侯行师",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["乙", "乙", "乙", "庚", "庚", "庚"],
               "branches": ["未", "巳", "卯", "午", "申", "戌"],
               "liu_qin": ["妻财", "子孙", "兄弟", "子孙", "官鬼", "妻财"]},
    "雷水解": {"code": "010100", "upper": "震", "lower": "坎", "number": 40, "sequence": 27, "palace": "震",
               "nature": "雷雨作", "attribute": "解除", "gua_ci": "利西南",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["戊", "戊", "戊", "庚", "庚", "庚"],
               "branches": ["寅", "辰", "午", "午", "申", "戌"],
               "liu_qin": ["兄弟", "妻财", "子孙", "子孙", "官鬼", "妻财"]},
    "雷风恒": {"code": "011100", "upper": "震", "lower": "巽", "number": 32, "sequence": 28, "palace": "震",
               "nature": "雷风相与", "attribute": "恒久", "gua_ci": "亨，无咎，利贞",
               "shi_yao": 3, "shi_type": "三世",
               "stems": ["辛", "辛", "辛", "庚", "庚", "庚"],
               "branches": ["丑", "亥", "酉", "午", "申", "戌"],
               "liu_qin": ["妻财", "父母", "官鬼", "子孙", "官鬼", "妻财"]},
    "地风升": {"code": "011000", "upper": "坤", "lower": "巽", "number": 46, "sequence": 29, "palace": "震",
               "nature": "地中生木", "attribute": "上升", "gua_ci": "元亨，用见大人",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["辛", "辛", "辛", "癸", "癸", "癸"],
               "branches": ["丑", "亥", "酉", "丑", "亥", "酉"],
               "liu_qin": ["妻财", "父母", "官鬼", "妻财", "父母", "官鬼"]},
    "水风井": {"code": "011010", "upper": "坎", "lower": "巽", "number": 48, "sequence": 30, "palace": "震",
               "nature": "木上有水", "attribute": "水井", "gua_ci": "改邑不改井",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["辛", "辛", "辛", "戊", "戊", "戊"],
               "branches": ["丑", "亥", "酉", "申", "戌", "子"],
               "liu_qin": ["妻财", "父母", "官鬼", "官鬼", "妻财", "父母"]},
    "泽风大过": {"code": "011110", "upper": "兑", "lower": "巽", "number": 28, "sequence": 31, "palace": "震",
                 "nature": "泽灭木", "attribute": "过度", "gua_ci": "栋桡，利有攸往",
                 "shi_yao": 4, "shi_type": "游魂",
                 "stems": ["辛", "辛", "辛", "丁", "丁", "丁"],
                 "branches": ["丑", "亥", "酉", "亥", "酉", "未"],
                 "liu_qin": ["妻财", "父母", "官鬼", "父母", "官鬼", "妻财"]},
    "泽雷随": {"code": "100110", "upper": "兑", "lower": "震", "number": 17, "sequence": 32, "palace": "震",
               "nature": "泽中有雷", "attribute": "随从", "gua_ci": "元亨利贞，无咎",
               "shi_yao": 3, "shi_type": "归魂",
               "stems": ["庚", "庚", "庚", "丁", "丁", "丁"],
               "branches": ["子", "寅", "辰", "亥", "酉", "未"],
               "liu_qin": ["父母", "兄弟", "妻财", "父母", "官鬼", "妻财"]},

    # 巽宫八卦（完整）
    "巽为风": {"code": "011011", "upper": "巽", "lower": "巽", "number": 57, "sequence": 33, "palace": "巽",
               "nature": "随风", "attribute": "顺从", "gua_ci": "小亨，利有攸往，利见大人",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["辛", "辛", "辛", "辛", "辛", "辛"],
               "branches": ["丑", "亥", "酉", "未", "巳", "卯"],
               "liu_qin": ["妻财", "父母", "官鬼", "妻财", "子孙", "兄弟"]},
    "风天小畜": {"code": "111011", "upper": "巽", "lower": "乾", "number": 9, "sequence": 34, "palace": "巽",
                 "nature": "风行天上", "attribute": "小积", "gua_ci": "亨。密云不雨",
                 "shi_yao": 1, "shi_type": "一世",
                 "stems": ["甲", "甲", "甲", "辛", "辛", "辛"],
                 "branches": ["子", "寅", "辰", "未", "巳", "卯"],
                 "liu_qin": ["父母", "兄弟", "妻财", "妻财", "子孙", "兄弟"]},
    "风火家人": {"code": "101011", "upper": "巽", "lower": "离", "number": 37, "sequence": 35, "palace": "巽",
                 "nature": "风自火出", "attribute": "家庭", "gua_ci": "利女贞",
                 "shi_yao": 2, "shi_type": "二世",
                 "stems": ["己", "己", "己", "辛", "辛", "辛"],
                 "branches": ["卯", "丑", "亥", "未", "巳", "卯"],
                 "liu_qin": ["兄弟", "妻财", "父母", "妻财", "子孙", "兄弟"]},
    "风雷益": {"code": "100011", "upper": "巽", "lower": "震", "number": 42, "sequence": 36, "palace": "巽",
               "nature": "风雷相益", "attribute": "增益", "gua_ci": "利有攸往，利涉大川",
               "shi_yao": 3, "shi_type": "三世",
               "stems": ["庚", "庚", "庚", "辛", "辛", "辛"],
               "branches": ["子", "寅", "辰", "未", "巳", "卯"],
               "liu_qin": ["父母", "兄弟", "妻财", "妻财", "子孙", "兄弟"]},
    "天雷无妄": {"code": "100111", "upper": "乾", "lower": "震", "number": 25, "sequence": 37, "palace": "巽",
                 "nature": "天下雷行", "attribute": "无妄", "gua_ci": "元亨利贞",
                 "shi_yao": 4, "shi_type": "四世",
                 "stems": ["庚", "庚", "庚", "壬", "壬", "壬"],
                 "branches": ["子", "寅", "辰", "午", "申", "戌"],
                 "liu_qin": ["父母", "兄弟", "妻财", "子孙", "官鬼", "妻财"]},
    "火雷噬嗑": {"code": "100101", "upper": "离", "lower": "震", "number": 21, "sequence": 38, "palace": "巽",
                 "nature": "电雷", "attribute": "咬合", "gua_ci": "亨，利用狱",
                 "shi_yao": 5, "shi_type": "五世",
                 "stems": ["庚", "庚", "庚", "己", "己", "己"],
                 "branches": ["子", "寅", "辰", "酉", "未", "巳"],
                 "liu_qin": ["父母", "兄弟", "妻财", "官鬼", "妻财", "子孙"]},
    "山雷颐": {"code": "100001", "upper": "艮", "lower": "震", "number": 27, "sequence": 39, "palace": "巽",
               "nature": "山下有雷", "attribute": "颐养", "gua_ci": "贞吉",
               "shi_yao": 4, "shi_type": "游魂",
               "stems": ["庚", "庚", "庚", "丙", "丙", "丙"],
               "branches": ["子", "寅", "辰", "戌", "子", "寅"],
               "liu_qin": ["父母", "兄弟", "妻财", "妻财", "父母", "兄弟"]},
    "山风蛊": {"code": "011001", "upper": "艮", "lower": "巽", "number": 18, "sequence": 40, "palace": "巽",
               "nature": "山下有风", "attribute": "蛊惑", "gua_ci": "元亨，利涉大川",
               "shi_yao": 3, "shi_type": "归魂",
               "stems": ["辛", "辛", "辛", "丙", "丙", "丙"],
               "branches": ["丑", "亥", "酉", "戌", "子", "寅"],
               "liu_qin": ["妻财", "父母", "官鬼", "妻财", "父母", "兄弟"]},

    # 坎宫八卦（完整）
    "坎为水": {"code": "010010", "upper": "坎", "lower": "坎", "number": 29, "sequence": 41, "palace": "坎",
               "nature": "水洊至", "attribute": "险陷", "gua_ci": "习坎，有孚维心，亨",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["戊", "戊", "戊", "戊", "戊", "戊"],
               "branches": ["子", "寅", "辰", "午", "申", "戌"],
               "liu_qin": ["兄弟", "官鬼", "父母", "妻财", "子孙", "兄弟"]},
    "水泽节": {"code": "110010", "upper": "坎", "lower": "兑", "number": 60, "sequence": 42, "palace": "坎",
               "nature": "泽上有水", "attribute": "节制", "gua_ci": "亨，苦节不可贞",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["丁", "丁", "丁", "戊", "戊", "戊"],
               "branches": ["巳", "卯", "丑", "午", "申", "戌"],
               "liu_qin": ["官鬼", "父母", "妻财", "妻财", "子孙", "兄弟"]},
    "水雷屯": {"code": "100010", "upper": "坎", "lower": "震", "number": 3, "sequence": 43, "palace": "坎",
               "nature": "雷雨济济", "attribute": "始生", "gua_ci": "元亨利贞，勿用有攸往",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["庚", "庚", "庚", "戊", "戊", "戊"],
               "branches": ["子", "寅", "辰", "午", "申", "戌"],
               "liu_qin": ["兄弟", "父母", "官鬼", "妻财", "子孙", "兄弟"]},
    "水火既济": {"code": "101010", "upper": "坎", "lower": "离", "number": 63, "sequence": 44, "palace": "坎",
                 "nature": "水在火上", "attribute": "完成", "gua_ci": "亨小，利贞",
                 "shi_yao": 3, "shi_type": "三世",
                 "stems": ["己", "己", "己", "戊", "戊", "戊"],
                 "branches": ["卯", "丑", "亥", "午", "申", "戌"],
                 "liu_qin": ["兄弟", "父母", "官鬼", "妻财", "子孙", "兄弟"]},
    "泽火革": {"code": "101110", "upper": "兑", "lower": "离", "number": 49, "sequence": 45, "palace": "坎",
               "nature": "泽中有火", "attribute": "变革", "gua_ci": "巳日乃孚",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["己", "己", "己", "丁", "丁", "丁"],
               "branches": ["卯", "丑", "亥", "亥", "酉", "未"],
               "liu_qin": ["兄弟", "父母", "官鬼", "父母", "妻财", "子孙"]},
    "雷火丰": {"code": "101100", "upper": "震", "lower": "离", "number": 55, "sequence": 46, "palace": "坎",
               "nature": "雷电皆至", "attribute": "丰盛", "gua_ci": "亨，王假之",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["己", "己", "己", "庚", "庚", "庚"],
               "branches": ["卯", "丑", "亥", "午", "申", "戌"],
               "liu_qin": ["兄弟", "父母", "官鬼", "子孙", "妻财", "父母"]},
    "地火明夷": {"code": "101000", "upper": "坤", "lower": "离", "number": 36, "sequence": 47, "palace": "坎",
                 "nature": "明入地中", "attribute": "光明受损", "gua_ci": "利艰贞",
                 "shi_yao": 4, "shi_type": "游魂",
                 "stems": ["己", "己", "己", "癸", "癸", "癸"],
                 "branches": ["卯", "丑", "亥", "丑", "亥", "酉"],
                 "liu_qin": ["兄弟", "父母", "官鬼", "父母", "官鬼", "妻财"]},
    "地水师": {"code": "010000", "upper": "坤", "lower": "坎", "number": 7, "sequence": 48, "palace": "坎",
               "nature": "地上有水", "attribute": "众聚", "gua_ci": "贞，丈人吉，无咎",
               "shi_yao": 3, "shi_type": "归魂",
               "stems": ["戊", "戊", "戊", "癸", "癸", "癸"],
               "branches": ["子", "寅", "辰", "丑", "亥", "酉"],
               "liu_qin": ["兄弟", "官鬼", "父母", "父母", "官鬼", "妻财"]},

    # 艮宫八卦（完整）
    "艮为山": {"code": "001001", "upper": "艮", "lower": "艮", "number": 52, "sequence": 49, "palace": "艮",
               "nature": "兼山", "attribute": "静止", "gua_ci": "艮其背，不获其身",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["丙", "丙", "丙", "丙", "丙", "丙"],
               "branches": ["辰", "午", "申", "戌", "子", "寅"],
               "liu_qin": ["兄弟", "父母", "官鬼", "妻财", "子孙", "兄弟"]},
    "山火贲": {"code": "101001", "upper": "艮", "lower": "离", "number": 22, "sequence": 50, "palace": "艮",
               "nature": "山下有火", "attribute": "文饰", "gua_ci": "亨，小利有攸往",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["己", "己", "己", "丙", "丙", "丙"],
               "branches": ["卯", "丑", "亥", "戌", "子", "寅"],
               "liu_qin": ["妻财", "官鬼", "子孙", "妻财", "子孙", "兄弟"]},
    "山天大畜": {"code": "111001", "upper": "艮", "lower": "乾", "number": 26, "sequence": 51, "palace": "艮",
                 "nature": "山在天上", "attribute": "大畜", "gua_ci": "利贞，不家食吉",
                 "shi_yao": 2, "shi_type": "二世",
                 "stems": ["甲", "甲", "甲", "丙", "丙", "丙"],
                 "branches": ["子", "寅", "辰", "戌", "子", "寅"],
                 "liu_qin": ["官鬼", "妻财", "子孙", "妻财", "子孙", "兄弟"]},
    "山泽损": {"code": "110001", "upper": "艮", "lower": "兑", "number": 41, "sequence": 52, "palace": "艮",
               "nature": "山下有泽", "attribute": "减损", "gua_ci": "有孚，元吉",
               "shi_yao": 3, "shi_type": "三世",
               "stems": ["丁", "丁", "丁", "丙", "丙", "丙"],
               "branches": ["巳", "卯", "丑", "戌", "子", "寅"],
               "liu_qin": ["兄弟", "父母", "官鬼", "妻财", "子孙", "兄弟"]},
    "火泽睽": {"code": "110101", "upper": "离", "lower": "兑", "number": 38, "sequence": 53, "palace": "艮",
               "nature": "上火下泽", "attribute": "乖离", "gua_ci": "小事吉",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["丁", "丁", "丁", "己", "己", "己"],
               "branches": ["巳", "卯", "丑", "酉", "未", "巳"],
               "liu_qin": ["兄弟", "父母", "官鬼", "兄弟", "父母", "官鬼"]},
    "天泽履": {"code": "110111", "upper": "乾", "lower": "兑", "number": 10, "sequence": 54, "palace": "艮",
               "nature": "天下有泽", "attribute": "慎行", "gua_ci": "履虎尾，不咥人，亨",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["丁", "丁", "丁", "壬", "壬", "壬"],
               "branches": ["巳", "卯", "丑", "午", "申", "戌"],
               "liu_qin": ["兄弟", "父母", "官鬼", "子孙", "妻财", "父母"]},
    "风泽中孚": {"code": "110011", "upper": "巽", "lower": "兑", "number": 61, "sequence": 55, "palace": "艮",
                 "nature": "泽上有风", "attribute": "诚信", "gua_ci": "豚鱼吉，利涉大川",
                 "shi_yao": 4, "shi_type": "游魂",
                 "stems": ["丁", "丁", "丁", "辛", "辛", "辛"],
                 "branches": ["巳", "卯", "丑", "未", "巳", "卯"],
                 "liu_qin": ["兄弟", "父母", "官鬼", "子孙", "兄弟", "妻财"]},
    "风山渐": {"code": "001011", "upper": "巽", "lower": "艮", "number": 53, "sequence": 56, "palace": "艮",
               "nature": "山上有风", "attribute": "渐进", "gua_ci": "女归吉，利贞",
               "shi_yao": 3, "shi_type": "归魂",
               "stems": ["丙", "丙", "丙", "辛", "辛", "辛"],
               "branches": ["辰", "午", "申", "未", "巳", "卯"],
               "liu_qin": ["兄弟", "父母", "官鬼", "子孙", "兄弟", "妻财"]},

    # 坤宫八卦（完整）
    "坤为地": {"code": "000000", "upper": "坤", "lower": "坤", "number": 2, "sequence": 57, "palace": "坤",
               "nature": "坤顺", "attribute": "纯阴", "gua_ci": "元亨利贞，利西南得朋，东北丧朋",
               "shi_yao": 6, "shi_type": "本宫",
               "stems": ["乙", "乙", "乙", "乙", "乙", "乙"],
               "branches": ["未", "巳", "卯", "丑", "亥", "酉"],
               "liu_qin": ["子孙", "妻财", "官鬼", "父母", "兄弟", "妻财"]},
    "地雷复": {"code": "100000", "upper": "坤", "lower": "震", "number": 24, "sequence": 58, "palace": "坤",
               "nature": "雷在地中", "attribute": "复苏", "gua_ci": "亨，出入无疾，朋来无咎",
               "shi_yao": 1, "shi_type": "一世",
               "stems": ["庚", "庚", "庚", "乙", "乙", "乙"],
               "branches": ["子", "寅", "辰", "丑", "亥", "酉"],
               "liu_qin": ["兄弟", "父母", "官鬼", "父母", "兄弟", "妻财"]},
    "地泽临": {"code": "110000", "upper": "坤", "lower": "兑", "number": 19, "sequence": 59, "palace": "坤",
               "nature": "泽上有地", "attribute": "降临", "gua_ci": "元亨利贞，至于八月有凶",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["丁", "丁", "丁", "乙", "乙", "乙"],
               "branches": ["巳", "卯", "丑", "丑", "亥", "酉"],
               "liu_qin": ["官鬼", "父母", "妻财", "父母", "兄弟", "妻财"]},
    "地天泰": {"code": "111000", "upper": "坤", "lower": "乾", "number": 11, "sequence": 60, "palace": "坤",
               "nature": "天地交泰", "attribute": "通泰", "gua_ci": "小往大来，吉亨",
               "shi_yao": 3, "shi_type": "三世",
               "stems": ["甲", "甲", "甲", "乙", "乙", "乙"],
               "branches": ["子", "寅", "辰", "丑", "亥", "酉"],
               "liu_qin": ["子孙", "兄弟", "妻财", "父母", "兄弟", "妻财"]},
    "泽天夬": {"code": "111110", "upper": "兑", "lower": "乾", "number": 43, "sequence": 61, "palace": "坤",
               "nature": "泽上于天", "attribute": "决断", "gua_ci": "扬于王庭",
               "shi_yao": 4, "shi_type": "四世",
               "stems": ["甲", "甲", "甲", "丁", "丁", "丁"],
               "branches": ["子", "寅", "辰", "亥", "酉", "未"],
               "liu_qin": ["子孙", "兄弟", "妻财", "子孙", "兄弟", "父母"]},
    "水天需": {"code": "111010", "upper": "坎", "lower": "乾", "number": 5, "sequence": 62, "palace": "坤",
               "nature": "云上于天", "attribute": "需待", "gua_ci": "有孚，光亨，贞吉",
               "shi_yao": 5, "shi_type": "五世",
               "stems": ["甲", "甲", "甲", "戊", "戊", "戊"],
               "branches": ["子", "寅", "辰", "申", "戌", "子"],
               "liu_qin": ["子孙", "兄弟", "妻财", "妻财", "父母", "子孙"]},
    "水地比": {"code": "000010", "upper": "坎", "lower": "坤", "number": 8, "sequence": 63, "palace": "坤",
               "nature": "地上有水", "attribute": "亲比", "gua_ci": "吉，原筮元永贞",
               "shi_yao": 4, "shi_type": "游魂",
               "stems": ["乙", "乙", "乙", "戊", "戊", "戊"],
               "branches": ["未", "巳", "卯", "申", "戌", "子"],
               "liu_qin": ["子孙", "妻财", "官鬼", "兄弟", "父母", "子孙"]},
    "泽地萃": {"code": "000110", "upper": "兑", "lower": "坤", "number": 45, "sequence": 64, "palace": "坤",
               "nature": "泽于地", "attribute": "聚集", "gua_ci": "亨，王假有庙",
               "shi_yao": 2, "shi_type": "二世",
               "stems": ["乙", "乙", "乙", "丁", "丁", "丁"],
               "branches": ["未", "巳", "卯", "亥", "酉", "未"],
               "liu_qin": ["父母", "官鬼", "妻财", "子孙", "兄弟", "父母"]}
}'''

# 使用eval安全地解析字典
old_dict = eval(old_dict_str)

# 创建新字典
new_dict = {}
for name, info in old_dict.items():
    # 获取code作为新的键
    code = info.get('code')
    if code:
        # 复制原始信息
        new_info = info.copy()
        # 删除'code'键并添加'name'键，值为原顶层键
        del new_info['code']
        new_info['name'] = name
        # 将新信息添加到新字典中
        new_dict[code] = new_info

# 将新字典转换为字符串格式
result_str = "SIXTY_FOUR_GUA = {\n"
for code, info in new_dict.items():
    result_str += f"    \"{code}\": {{\n"
    # 添加name字段在最前面
    result_str += f"        \"name\": \"{info['name']}\",\n"
    # 添加其他字段
    for key, value in info.items():
        if key != 'name':
            if isinstance(value, str):
                # 对字符串值添加引号
                result_str += f"        \"{key}\": \"{value}\",\n"
            else:
                # 非字符串值直接输出
                result_str += f"        \"{key}\": {value},\n"
    # 移除最后一个逗号并闭合大括号
    result_str = result_str.rstrip(',\n') + '\n    },\n'
# 移除最后一个逗号并闭合大括号
result_str = result_str.rstrip(',\n') + '\n}'

# 保存结果到文件
with open('rebuild_gua_result.txt', 'w', encoding='utf-8') as f:
    f.write(result_str)

print(f"成功重构了{len(new_dict)}个卦象条目")
print("重构后的字典已保存到 rebuild_gua_result.txt")
